// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbiYT_1sQTI8NOdLzwJFPP-3e5OVZtNzc',
    appId: '1:366310860834:web:7d45f4d9b5f1343ae9c27b',
    messagingSenderId: '366310860834',
    projectId: 'focus-one-dfaf6',
    authDomain: 'focus-one-dfaf6.firebaseapp.com',
    storageBucket: 'focus-one-dfaf6.firebasestorage.app',
    measurementId: 'G-RLBZ3RT2ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSNkcLrnUZQBBeFPFHjRTKwo2t5xv89k',
    appId: '1:366310860834:android:a9f602cc287144b7e9c27b',
    messagingSenderId: '366310860834',
    projectId: 'focus-one-dfaf6',
    storageBucket: 'focus-one-dfaf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7UOr1Hat651VDBD64-guleuRkTL3CTFU',
    appId: '1:366310860834:ios:4d15371af4d8adc0e9c27b',
    messagingSenderId: '366310860834',
    projectId: 'focus-one-dfaf6',
    storageBucket: 'focus-one-dfaf6.firebasestorage.app',
    iosBundleId: 'com.example.focusOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7UOr1Hat651VDBD64-guleuRkTL3CTFU',
    appId: '1:366310860834:ios:4d15371af4d8adc0e9c27b',
    messagingSenderId: '366310860834',
    projectId: 'focus-one-dfaf6',
    storageBucket: 'focus-one-dfaf6.firebasestorage.app',
    iosBundleId: 'com.example.focusOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbiYT_1sQTI8NOdLzwJFPP-3e5OVZtNzc',
    appId: '1:366310860834:web:cdb912e39bc57189e9c27b',
    messagingSenderId: '366310860834',
    projectId: 'focus-one-dfaf6',
    authDomain: 'focus-one-dfaf6.firebaseapp.com',
    storageBucket: 'focus-one-dfaf6.firebasestorage.app',
    measurementId: 'G-XE8C85FRPL',
  );
}